name: Release Marrow

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Triggers when you push a tag like v0.1.0

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build and Upload Binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (optional) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
          # Note that glob pattern is not supported yet.
          bin: marrow # Must match Cargo.toml [package] name / default binary name
          # rename the binary in the tarball to 'marrow'
          archive: marrow-${{ matrix.target }}
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}